# Railway configuration for PHP Backend
[build]
  builder = "heroku/php"
  buildCommand = "composer install --no-dev --optimize-autoloader"

[deploy]
  startCommand = "cd finance-backend && php -S 0.0.0.0:$PORT -t ."
  healthcheckPath = "/health.php"
  healthcheckTimeout = 100
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3

[env]
  PHP_VERSION = "8.1"
  COMPOSER_ALLOW_SUPERUSER = "1"
  APP_ENV = "production"
  APP_DEBUG = "false"
